name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (base) docker build push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: base.Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/manualpilot/browser:base,ghcr.io/manualpilot/browser:latest

      - name: (batteries) docker build push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: batteries.Dockerfile
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/manualpilot/browser:batteries
